spring:
  datasource:
    url: jdbc:sqlserver://f1ecommerce.database.windows.net:1433;database=f1ecommercedb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: f1ecommerce
    password: ecommerceF1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191